@echo off
cd /d "%~dp0"
echo Starting local development server...
echo Setting DATABASE_URL to SQLite...
set DATABASE_URL=file:./dev.db
echo Running database setup...
npx prisma generate
npx prisma migrate dev --name local-init
echo Starting Next.js development server...
npm run dev
